<?xml version="1.0"?>
<package format="3">
  <name>stereo_depth</name>
  <version>0.1.0</version>
  <description>stereo depth for single drone navigation</description>
  <maintainer email="team@example.com">PingTIKES</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>cv_bridge</depend>
  <depend>message_filters</depend>
  <depend>python3-numpy</depend>
  <depend>python3-opencv</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>vio_bridge</depend>
  <export><build_type>ament_python</build_type></export>
</package>
