<?xml version="1.0"?>
<package format="3">
  <name>goal_manager</name>
  <version>0.1.0</version>
  <description>goal manager for single drone navigation</description>
  <maintainer email="team@example.com">PingTIKES</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <export><build_type>ament_python</build_type></export>
</package>
