<?xml version="1.0"?>
<package format="3">
  <name>one_drone_bringup</name>
  <version>0.1.0</version>
  <description>Single-drone Gazebo sensor and OpenVINS/Nav2/PX4 navigation launch</description>
  <maintainer email="team@example.com">PingTIKES</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ov_msckf</exec_depend>
  <exec_depend>uav_localization</exec_depend>
  <exec_depend>uav_perception</exec_depend>
  <exec_depend>modify_map_to_odom</exec_depend>
  <exec_depend>rviz_tf_shift</exec_depend>
  <exec_depend>one_drone_navigation</exec_depend>
  <exec_depend>one_drone_control</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
